// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsPAboTR5umfqpU6e8Kndc_DXIGHpwxbE',
    appId: '1:649906619226:web:76c01eba1e87bc0d676963',
    messagingSenderId: '649906619226',
    projectId: 'mapman-4ac03',
    authDomain: 'mapman-4ac03.firebaseapp.com',
    storageBucket: 'mapman-4ac03.firebasestorage.app',
    measurementId: 'G-T8THVKGDWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsCq74MaS-KR_dcauwqLvJmWrK0pP2ow',
    appId: '1:649906619226:android:19b3f7e4af00862e676963',
    messagingSenderId: '649906619226',
    projectId: 'mapman-4ac03',
    storageBucket: 'mapman-4ac03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBedbEcj--Xe8kxL87It7nrq5Gi2d-qIKU',
    appId: '1:649906619226:ios:e859119c3f128485676963',
    messagingSenderId: '649906619226',
    projectId: 'mapman-4ac03',
    storageBucket: 'mapman-4ac03.firebasestorage.app',
    iosBundleId: 'com.mapman.mapman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBedbEcj--Xe8kxL87It7nrq5Gi2d-qIKU',
    appId: '1:649906619226:ios:e859119c3f128485676963',
    messagingSenderId: '649906619226',
    projectId: 'mapman-4ac03',
    storageBucket: 'mapman-4ac03.firebasestorage.app',
    iosBundleId: 'com.mapman.mapman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsPAboTR5umfqpU6e8Kndc_DXIGHpwxbE',
    appId: '1:649906619226:web:02dadd26774db2f2676963',
    messagingSenderId: '649906619226',
    projectId: 'mapman-4ac03',
    authDomain: 'mapman-4ac03.firebaseapp.com',
    storageBucket: 'mapman-4ac03.firebasestorage.app',
    measurementId: 'G-0Z8QER8VNX',
  );
}
